-- InstanceDungeonsData.lua
-- Diese Tabelle enthält für jeden klassischen Dungeon
-- Trage bei "requiredKills" die entsprechenden Zahlen ein.

InstanceDungeonsData = {
    ["Gnomeregan"] = {
        { bossName = "Viscous Fallout",       requiredKills = 5 },
        { bossName = "Electrocutioneer 6000", requiredKills = 25 },
        { bossName = "Crowd Pummeler 9-60",   requiredKills = 50 },
        { bossName = "Mekgineer Thermaplugg", requiredKills = 60 },
    },
    ["Deadmines"] = {
	    { bossName = "Rhahk'Zor",            requiredKills = 20 },
	    { bossName = "Sneed",                requiredKills = 40 },
	    { bossName = "Gilnid",               requiredKills = 55 },
	    { bossName = "Cookie",               requiredKills = 75 },
	    { bossName = "Mr.Smite",             requiredKills = 80 },
	    { bossName = "Captain Greenskin",    requiredKills = 85 },
        { bossName = "Edwin VanCleef",       requiredKills = 90 },
    },
    ["Stormwind Stockade"] = {
        { bossName = "Targorr the Dread",     requiredKills = 10 },
        { bossName = "Kam Deepfury",          requiredKills = 15 },
        { bossName = "Hamhock",               requiredKills = 20 },
        { bossName = "Bazil Thredd",          requiredKills = 25 },
        { bossName = "Dextren Ward",          requiredKills = 25 },
    },
    ["Ragefire Chasm"] = {
	    { bossName = "Oggleflint",           requiredKills = 20 },
	    { bossName = "Taragaman the Hungerer", requiredKills = 40 },
	    { bossName = "Jergosh the Invoker",  requiredKills = 50 },
	    { bossName = "Bazzalan",             requiredKills = 70 },
    },
    ["Razorfen Downs"] = {
	    { bossName = "Glutton",              requiredKills = 20 },
	    { bossName = "Tuten'kash",           requiredKills = 30 },
	    { bossName = "Mordresh Fire Eye",    requiredKills = 40 },
	    { bossName = "Ammenar the Coldbringer",requiredKills = 60 },
    },
    ["Razorfen Kraul"] = {
	    { bossName = "Aggem Thorncurse",     requiredKills = 30 },
	    { bossName = "Death Speaker Jargba", requiredKills = 35 },
	    { bossName = "Overlord Ramtusk",     requiredKills = 40 },
	    { bossName = "Agthelos the Raging",  requiredKills = 60 },
        { bossName = "Charlga Razorflank",   requiredKills = 65 },
    },
    ["Scarlet Monastery"] = {
	    { bossName = "High Inquisitor Fairbanks",     requiredKills = 30 },
	    { bossName = "High Inquisitor Whitemane", requiredKills = 40 },
	    { bossName = "Scarlet Commander Mograine",     requiredKills = 40 },
    },
    ["Shadowfang Keep"] = {
        { bossName = "Rethilgore",            requiredKills = 10 },
        { bossName = "Baron Silverlaine",     requiredKills = 30 },
        { bossName = "Commander Springvale",  requiredKills = 40 },
        { bossName = "Odo the Blindwatcher",  requiredKills = 50 },
        { bossName = "Fenrus the Devourer",   requiredKills = 60 },
        { bossName = "Wolfmaster Nandos",     requiredKills = 65 },
        { bossName = "Archmage Argus",        requiredKills = 65 },
    },
    ["Wailing Caverns"] = {
        { bossName = "Kresh",                 requiredKills = 10 },
        { bossName = "Lord Cobrahn",          requiredKills = 40 },
        { bossName = "Lord Pythas",           requiredKills = 50 },
        { bossName = "Skum",                  requiredKills = 60 },
        { bossName = "Verdan the Everliving", requiredKills = 70 },
        { bossName = "Lord Serpentis",        requiredKills = 70 },
        { bossName = "Mutanus the Devourer",   requiredKills = 90 },
    },
    ["Blackrock Depths"] = {
        { bossName = "Bael'Gar",	                requiredKills = 15},
        { bossName = "High Interrogator Gerstahn",  requiredKills = 15},
        { bossName = "Lord Roccor",	                requiredKills = 30},
        { bossName = "Lord Incendius",	            requiredKills = 35},
        { bossName = "Fineous Darkvire",            requiredKills = 45},
        { bossName = "Gorosh the Dervish",	        requiredKills = 45},
        { bossName = "Doom'rel",	                requiredKills = 55},
        { bossName = "Plugger Spazzring",           requiredKills = 75},
        { bossName = "Warder Stilgiss",	            requiredKills = 85},
        { bossName = "Phalanx",	                    requiredKills = 85},
        { bossName = "General Angerforge",	        requiredKills = 90},
        { bossName = "Golem Lord Argelmach",	    requiredKills = 95},
        { bossName = "Ambassador Flamelash",	    requiredKills = 100},
        { bossName = "Magmus",	                    requiredKills = 130},
        { bossName = "Emperor Dargran Thaurissan",	requiredKills = 145},
        },
    ["Scholomance"] = {
        { bossName = "Jandice Barov",   requiredKills = 45 },
        { bossName = "Marduk Blackpool",      requiredKills = 55 },
        { bossName = "Rattlegore", requiredKills = 65 },
        { bossName = "Vectus",          requiredKills = 65 },
        { bossName = "Ras Frosthwhisper", requiredKills = 80 },
        { bossName = "Instructor Malicia",  requiredKills = 100 },
        { bossName = "Doctor Theolen Krastinov", requiredKills = 105 },
        { bossName = "Lorekeeper Polkelt", requiredKills = 110 },
        { bossName = "Lady Illucia Barov",    requiredKills = 125 },
        { bossName = "Lord Alexei Barov", requiredKills = 135 },
        { bossName = "The Ravenian", requiredKills = 145 },
        { bossName = "Darkmaster Gandling",   requiredKills = 150 },
    },
    ["Stratholme"] = {
        { bossName = "Baroness Anastari", requiredKills = 30 },
        { bossName = "Nerub'enkan",         requiredKills = 30 },
        { bossName = "The Unforgiven",       requiredKills = 55 },
        { bossName = "Malor The Zealous",       requiredKills = 65 },
        { bossName = "Maleki the Pallid",    requiredKills = 65 },
        { bossName = "Canon Master Willey",     requiredKills = 85 },
        { bossName = "Archivist Galford",         requiredKills = 100 },
        { bossName = "Ramstein the Gorger",     requiredKills = 110 },
        { bossName = "Baron Rivendare",             requiredKills = 130 },
    },
    ["Uldaman"] = {
        { bossName = "Revelosh",              requiredKills = 10 },
        { bossName = "Baelog",             requiredKills = 15 },
        { bossName = "Ironaya",             requiredKills = 30 },
        { bossName = "Ancient Stone Keeper",  requiredKills = 35 },
        { bossName = "Galgann Firehammer",    requiredKills = 45 },
        { bossName = "Grimlok",             requiredKills = 60 },
        { bossName = "Archaedas",             requiredKills = 70 },
    },
    ["Zul'Farrak"] = {
        { bossName = "Theka the Martyr",        requiredKills = 25 },
        { bossName = "Antu'sul",              requiredKills = 35 },
        { bossName = "Witch Doctor Zum'rah",    requiredKills = 40 },
        { bossName = "Shadowpriest Sezz'ziz",   requiredKills = 65 },
        { bossName = "Nekrum Gutchewer",        requiredKills = 65 },
        { bossName = "Chief Ukorz Sandscalp",   requiredKills = 70 },
        { bossName = "Hydromancer Velrath",     requiredKills = 70 },
        { bossName = "Gahz'rilla",              requiredKills = 70 },
    },
    ["Auchindoun: Mana-Tombs"] = {
        { bossName = "Pandemonius",        requiredKills = 10 },
        { bossName = "Tavarok",              requiredKills = 40 },
        { bossName = "Nexus-Prince Shaffar",    requiredKills = 80 },
    },
    ["Auchindoun: Sethekk Halls"] = {
        { bossName = "Darkweaver Syth",        requiredKills = 25 },
        { bossName = "Anzu",              requiredKills = 50 },
        { bossName = "Talonking Ikiss",    requiredKills = 90 },
    },
    ["Auchindoun: Shadow Labyrinth"] = {
        { bossName = "Ambassador Hellmaw",        requiredKills = 30 },
        { bossName = "Blackheart the Inciter",   requiredKills = 50 },
        { bossName = "Grandmaster Vorpil",    requiredKills = 80 },
        { bossName = "Murmur",    requiredKills = 110 },
    },
    ["Auchindoun: Crypts"] = {
        { bossName = "Shirrak the Dead Watcher",        requiredKills = 25 },
        { bossName = "Exarch Maladaar",              requiredKills = 50 },
    },
    ["Coilfang: The Underbog"] = {
        { bossName = "Hungarfen",        requiredKills = 15 },
        { bossName = "Ghaz'an",              requiredKills = 50 },
        { bossName = "Swamplord Musel'ek",    requiredKills = 65 },
        { bossName = "The Black Stalker",    requiredKills = 75 },
    },
    ["Coilfang: The Slave Pens"] = {
        { bossName = "Mennu the Betrayer",        requiredKills = 30 },
        { bossName = "Rokmar the Crackler",              requiredKills = 45 },
        { bossName = "Quagmirran",    requiredKills = 70 },
    },
    ["Coilfang: The Steamvault"] = {
        { bossName = "Hydromancer Thesoia",        requiredKills = 25 },
        { bossName = "Mekgineer Steamrigger",              requiredKills = 60 },
        { bossName = "Warlord Kalitresh",    requiredKills = 90 },
    },
    ["Hellfire Citadel: Ramparts"] = {
        { bossName = "Watchkeeper Gargolmar",        requiredKills = 35 },
        { bossName = "Omor the Unscarred",              requiredKills = 50 },
        { bossName = "Vazruden the Herald",    requiredKills = 60 },
    },
    ["Hellfire Citadel: The Blood Furnace"] = {
        { bossName = "The Maker",        requiredKills = 30 },
        { bossName = "Broggok",              requiredKills = 70 },
        { bossName = "Keli'dan the Breaker",    requiredKills = 90 },
    },
    ["Hellfire Citadel: The Shattered Halls"] = {
        { bossName = "Grand Warlock Nethekurse",        requiredKills = 70 },
        { bossName = "Blood Guard Porung",              requiredKills = 85 },
        { bossName = "Warbringer O'mrogg",        requiredKills = 120 },
        { bossName = "Warchief Kargath Bladefist",    requiredKills = 140 },
    },
    ["Tempest Keep: The Botanica"] = {
        { bossName = "Commander Sarannis",        requiredKills = 30 },
        { bossName = "High Botanist Freywinn",    requiredKills = 45 },
        { bossName = "Thorngrin the Tender",        requiredKills = 60 },
        { bossName = "Laj",              requiredKills = 85 },
        { bossName = "Warp Splinter",    requiredKills = 100 },
    },
    ["Tempest Keep: The Arcatraz"] = {
        { bossName = "Zereketh the Unbound",        requiredKills = 15 },
        { bossName = "Dalliah the Doomsayer",    requiredKills = 40 },
        { bossName = "Wrath-Scryer Soccothrates",        requiredKills = 40 },
        { bossName = "Harbinger Skyriss",              requiredKills = 60 },
    },
    ["Tempest Keep: The Mechanar"] = {
        { bossName = "Mechano-Lord",                    requiredKills = 20 },
        { bossName = "Nethermancer Sepethrea",          requiredKills = 30 },
        { bossName = "Pathaleon the Calculator",        requiredKills = 50 },
    },
    ["Black Temple"] = {
        { bossName = "High Warlord Najentus",   requiredKills = 10 },
        { bossName = "Supremus",                requiredKills = 30 },
        { bossName = "Shade of Akama",          requiredKills = 60 },
        { bossName = "Teron Gorefiend",         requiredKills = 80 },
        { bossName = "Gurtogg Bloodboil",       requiredKills = 90 },
        { bossName = "Reliquary of Souls",      requiredKills = 120 },
        { bossName = "Mother Shahraz",          requiredKills = 210 },
        { bossName = "Illidan Stormrage",       requiredKills = 250 },
    },
    ["Karazhan"] = {
        { bossName = "Attumen the Huntsman",     requiredKills = 20 },
        { bossName = "Moroes",                  requiredKills = 30 },
        { bossName = "Nightbane",                  requiredKills = 50 },
        { bossName = "Maiden of Virtue",        requiredKills = 90 },
        { bossName = "The Big Bad Wolf",             requiredKills = 100 },
        { bossName = "The Curator",             requiredKills = 120 },
        { bossName = "Terestian Illhoof",       requiredKills = 150 },
        { bossName = "Shade of Aran",           requiredKills = 190 },
        { bossName = "Netherspite",             requiredKills = 210 },
        { bossName = "Prince Malchezaar",       requiredKills = 230 },
    },
    ["Molten Core"] = {
        { bossName = "Lucifron",                requiredKills = 20 },
        { bossName = "Magmadar",                 requiredKills = 25 },
        { bossName = "Gehennas",                 requiredKills = 10 },
        { bossName = "Garr",                     requiredKills = 20 },
        { bossName = "Baron Geddon",             requiredKills = 35 },
        { bossName = "Shazzrah",                 requiredKills = 30 },
        { bossName = "Sulfuron Harbinger",        requiredKills = 50 },
        { bossName = "Golemagg the Incinerator", requiredKills = 60 },
        { bossName = "Ragnaros",                 requiredKills = 65 },
    },
    ["Blackwing Lair"] = {
        { bossName = "Razorgore the Untamed",    requiredKills = 2 },
        { bossName = "Vaelastrasz the Corrupt",   requiredKills = 2 },
        { bossName = "Broodlord Lashlayer",       requiredKills = 70 },
        { bossName = "Firemaw",                   requiredKills = 80 },
        { bossName = "Ebonroc",                   requiredKills = 90 },
        { bossName = "Flamegor",                  requiredKills = 65 },
        { bossName = "Chromaggus",                requiredKills = 100 },
        { bossName = "Nefarian",                  requiredKills = 110 },
    },
    ["Zul'Gurub!"] = {
        { bossName = "High Priest Venoxis",     requiredKills = 0 },
        { bossName = "High Priestess Jeklik",    requiredKills = 0 },
        { bossName = "High Priestess Mar'li",    requiredKills = 0 },
        { bossName = "High Priest Thekal",       requiredKills = 0 },
        { bossName = "High Priestess Arlokk",    requiredKills = 0 },
        { bossName = "Hakkar the Soulflayer",    requiredKills = 0 },
    },
    ["Ahn'Qiraj Temple"] = {
        { bossName = "The Prophet Skeram",      requiredKills = 5 },
        { bossName = "Vem",                     requiredKills = 25 },
        { bossName = "Princess Huhuran",        requiredKills = 25 },
        { bossName = "Ouro",                    requiredKills = 25 },
        { bossName = "Battleguard Sartura",     requiredKills = 35 },
        { bossName = "Fankriss the Unyielding", requiredKills = 65 },
        { bossName = "Viscidus",                requiredKills = 65 },
        { bossName = "C'Thun",                  requiredKills = 85 },
    },
    ["Ruins of Ahn'Qiraj!"] = {
        { bossName = "Ayamiss the Hunter",      requiredKills = 0 },
        { bossName = "Buru the Gorger",         requiredKills = 0 },
        { bossName = "Ossirian the Unscarred",  requiredKills = 0 },
    },
    ["Naxxramas!"] = {
        { bossName = "Anub'Rekhan",             requiredKills = 0 },
        { bossName = "Grand Widow Faerlina",    requiredKills = 0 },
        { bossName = "Maexxna",                 requiredKills = 0 },
        { bossName = "Instructor Razuvious",    requiredKills = 0 },
        { bossName = "Gothik the Harvester",    requiredKills = 0 },
        { bossName = "The Four Horsemen",       requiredKills = 0 },
        { bossName = "Patchwerk",               requiredKills = 0 },
        { bossName = "Grobbulus",               requiredKills = 0 },
        { bossName = "Gluth",                   requiredKills = 0 },
        { bossName = "Thaddius",                requiredKills = 0 },
        { bossName = "Sapphiron",               requiredKills = 0 },
        { bossName = "Kel'Thuzad",              requiredKills = 0 },
    },
    ["Onyxia's Lair!"] = {
        { bossName = "Onyxia",                  requiredKills = 0 },
    },
    ["Coilfang: Serpentshrine Cavern"] = {
        { bossName = "Hydross the Unstable",    requiredKills = 15 },
        { bossName = "The Lurker Below",        requiredKills = 20 },
        { bossName = "Leotheras the Blind",     requiredKills = 40 },
        { bossName = "Fathom-Lord Karathress",    requiredKills = 50 },
        { bossName = "Morogrim Tidewalker",    requiredKills = 60 },
        { bossName = "Lady Vashj",       requiredKills = 90 },
    },
    ["Tempest Keep"] = {
        { bossName = "Al'ar",    requiredKills = 20 },
        { bossName = "Void Reaver",        requiredKills = 40 },
        { bossName = "High Astromancer Solarian",    requiredKills = 40 },
        { bossName = "Kael'thas Sunstrider",    requiredKills = 65 },
    },
    ["Gruul's Lair"] = {
        { bossName = "High King Maulgar",                  requiredKills = 2 },
        { bossName = "Gruul the Dragonkiller",             requiredKills = 10 },
    },
    ["Magtheridon's Lair"] = {
        { bossName = "Maghteridon",                  requiredKills = 5 },
    },
    ["The Sunwell"] = {
        { bossName = "Kalecgos",    requiredKills = 30 },
        { bossName = "Brutallus",        requiredKills = 40 },
        { bossName = "Felmyst",     requiredKills = 40 },
        { bossName = "Eredar Twins",    requiredKills = 70 },
        { bossName = "M'uru",    requiredKills = 90 },
        { bossName = "Kil'jaeden",       requiredKills = 100 },
    },
    ["Zul'Aman"] = {
        { bossName = "Akil'zon",    requiredKills = 10 },
        { bossName = "Nalorakk",        requiredKills = 20 },
        { bossName = "Jan'alai",    requiredKills = 40 },
        { bossName = "Halazzi",    requiredKills = 50 },
        { bossName = "Hex Lord Malacrass",    requiredKills = 60 },
        { bossName = "Zul'jin",    requiredKills = 65 },
    },
    ["Azjol-Nerub"] = {
        { bossName = "Krik'thir the Gatewatcher",    requiredKills = 5 },
        { bossName = "Hadronox",        requiredKills = 15 },
        { bossName = "Anub'arak",    requiredKills = 35 },
    },
    ["Utgarde Keep"] = {
        { bossName = "Prince Keleseth",    requiredKills = 15 },
        { bossName = "Dalronn the Controller",        requiredKills = 40 },
        { bossName = "Ingvar the Plunderer",    requiredKills = 60 },
    },
    ["The Nexus"] = {
        { bossName = "Grand Magus Telestra",    requiredKills = 20 },
        { bossName = "Anomalus",        requiredKills = 50 },
        { bossName = "Ormorokk the Tree-Shaper",    requiredKills = 90 },
        { bossName = "Keristrasza",    requiredKills = 110 },
    },
    ["Ahn'Kahet: The Old Kingdom"] = {
        { bossName = "Elder Nadox",    requiredKills = 15 },
        { bossName = "Prince Taldaraan",        requiredKills = 30 },
        { bossName = "Amanitar",    requiredKills = 40 },
        { bossName = "Jedoga Shadowseeker",    requiredKills = 50 },
        { bossName = "Herold Volazj",    requiredKills = 55 },
    },
    ["Halls of Lightning"] = {
        { bossName = "General Bjarngrim",    requiredKills = 5 },
        { bossName = "Volkhan",        requiredKills = 30 },
        { bossName = "Ionar",    requiredKills = 50 },
        { bossName = "Loken",    requiredKills = 75 },
    },
    ["Halls of Stone"] = {
        { bossName = "Krystallus",    requiredKills = 40 },
        { bossName = "Maiden of Grief",        requiredKills = 60 },
        { bossName = "Sjonnar the Ironshaper",    requiredKills = 80 },
    },
    ["Gundrak"] = {
        { bossName = "Moorabi",    requiredKills = 5 },
        { bossName = "Draakari Elemental",        requiredKills = 10 },
        { bossName = "Slad'ran",    requiredKills = 25 },
        { bossName = "Gal'Darah",    requiredKills = 35 },
    },
    

}

