-- InstanceRaidsData.lua
-- Diese Tabelle enthält für jeden klassischen Raid die gewünschte Liste
-- Trage bei "requiredKills" die entsprechenden Zahlen ein.

InstanceRaidsData = {
    ["Molten Core"] = {
        { bossName = "Lucifron",                requiredKills = 0 },
        { bossName = "Magmadar",                 requiredKills = 0 },
        { bossName = "Gehennas",                 requiredKills = 0 },
        { bossName = "Garr",                     requiredKills = 0 },
        { bossName = "Baron Geddon",             requiredKills = 0 },
        { bossName = "Shazzrah",                 requiredKills = 0 },
        { bossName = "Sulfuron Harbinger",        requiredKills = 0 },
        { bossName = "Golemagg the Incinerator", requiredKills = 0 },
        { bossName = "Majordomo Executus",       requiredKills = 0 },
        { bossName = "Ragnaros",                 requiredKills = 0 },
    },
    ["Blackwing Lair"] = {
        { bossName = "Razorgore the Untamed",    requiredKills = 0 },
        { bossName = "Vaelastrasz the Corrupt",   requiredKills = 0 },
        { bossName = "Broodlord Lashlayer",       requiredKills = 0 },
        { bossName = "Firemaw",                   requiredKills = 0 },
        { bossName = "Ebonroc",                   requiredKills = 0 },
        { bossName = "Flamegor",                  requiredKills = 0 },
        { bossName = "Chromaggus",                requiredKills = 0 },
        { bossName = "Nefarian",                  requiredKills = 0 },
    },
    ["Zul'Gurub"] = {
        { bossName = "High Priest Venoxis",     requiredKills = 0 },
        { bossName = "High Priestess Jeklik",    requiredKills = 0 },
        { bossName = "High Priestess Mar'li",    requiredKills = 0 },
        { bossName = "High Priest Thekal",       requiredKills = 0 },
        { bossName = "High Priestess Arlokk",    requiredKills = 0 },
        { bossName = "Hakkar the Soulflayer",    requiredKills = 0 },
    },
    ["Temple of Ahn'Qiraj"] = {
        { bossName = "The Prophet Skeram",      requiredKills = 0 },
        { bossName = "Vem",                     requiredKills = 0 },
        { bossName = "Kri",                     requiredKills = 0 },
        { bossName = "Ouro",                    requiredKills = 0 },
        { bossName = "C'Thun",                  requiredKills = 0 },
    },
    ["Ruins of Ahn'Qiraj"] = {
        { bossName = "Ayamiss the Hunter",      requiredKills = 0 },
        { bossName = "Buru the Gorger",         requiredKills = 0 },
        { bossName = "Ossirian the Unscarred",  requiredKills = 0 },
    },
    ["Naxxramas"] = {
	
        { bossName = "Noth the Plaquebringer",  requiredKills = 10 },
        { bossName = "Anub'Rekhan",             requiredKills = 10 },
        { bossName = "Grand Widow Faerlina",    requiredKills = 50 },
        { bossName = "Maexxna",                 requiredKills = 80 },
        { bossName = "Instructor Razuvious",    requiredKills = 25 },
        { bossName = "Gothik the Harvester",    requiredKills = 35 },
        { bossName = "Heigan the Unclean",             requiredKills = 40 },
        { bossName = "The Four Horsemen",       requiredKills = 60 },
        { bossName = "Patchwerk",               requiredKills = 30 },
        { bossName = "Grobbulus",               requiredKills = 35 },
        { bossName = "Gluth",                   requiredKills = 35 },
        { bossName = "Thaddius",                requiredKills = 35 },
        { bossName = "Loatheb",             requiredKills = 80 },
        { bossName = "Sapphiron",               requiredKills = 200 },
        { bossName = "Kel'Thuzad",              requiredKills = 210 },
    },
    ["Onyxia's Lair"] = {
        { bossName = "Onyxia",                  requiredKills = 0 },
    },
    ["The Obsidian Sanctum"] = {
        { bossName = "Vesperon", requiredKills = 5 },
        { bossName = "Tenebron",    requiredKills = 10 },
        { bossName = "Shadron",        requiredKills = 10 },
        { bossName = "Sartharion",    requiredKills = 15 },
    },
     ["Black Temple"] = {
        { bossName = "High Warlord Najentus",   requiredKills = 10 },
        { bossName = "Supremus",                requiredKills = 30 },
        { bossName = "Shade of Akama",          requiredKills = 60 },
        { bossName = "Teron Gorefiend",         requiredKills = 80 },
        { bossName = "Gurtogg Bloodboil",       requiredKills = 90 },
        { bossName = "Reliquary of Souls",      requiredKills = 120 },
        { bossName = "Mother Shahraz",          requiredKills = 210 },
        { bossName = "Illidan Stormrage",       requiredKills = 250 },
    },
    ["Karazhan"] = {
        { bossName = "Attumen the Huntsman",     requiredKills = 20 },
        { bossName = "Moroes",                  requiredKills = 30 },
        { bossName = "Nightbane",                  requiredKills = 50 },
        { bossName = "Maiden of Virtue",        requiredKills = 90 },
        { bossName = "The Big Bad Wolf",             requiredKills = 100 },
        { bossName = "The Curator",             requiredKills = 120 },
        { bossName = "Terestian Illhoof",       requiredKills = 150 },
        { bossName = "Shade of Aran",           requiredKills = 190 },
        { bossName = "Netherspite",             requiredKills = 210 },
        { bossName = "Prince Malchezaar",       requiredKills = 230 },
    },
    ["Molten Core"] = {
        { bossName = "Lucifron",                requiredKills = 20 },
        { bossName = "Magmadar",                 requiredKills = 25 },
        { bossName = "Gehennas",                 requiredKills = 10 },
        { bossName = "Garr",                     requiredKills = 20 },
        { bossName = "Baron Geddon",             requiredKills = 35 },
        { bossName = "Shazzrah",                 requiredKills = 30 },
        { bossName = "Sulfuron Harbinger",        requiredKills = 50 },
        { bossName = "Golemagg the Incinerator", requiredKills = 60 },
        { bossName = "Ragnaros",                 requiredKills = 65 },
    },
    ["Blackwing Lair"] = {
        { bossName = "Razorgore the Untamed",    requiredKills = 2 },
        { bossName = "Vaelastrasz the Corrupt",   requiredKills = 2 },
        { bossName = "Broodlord Lashlayer",       requiredKills = 70 },
        { bossName = "Firemaw",                   requiredKills = 80 },
        { bossName = "Ebonroc",                   requiredKills = 90 },
        { bossName = "Flamegor",                  requiredKills = 65 },
        { bossName = "Chromaggus",                requiredKills = 100 },
        { bossName = "Nefarian",                  requiredKills = 110 },
    },
    ["Ahn'Qiraj Temple"] = {
        { bossName = "The Prophet Skeram",      requiredKills = 5 },
        { bossName = "Vem",                     requiredKills = 25 },
        { bossName = "Princess Huhuran",        requiredKills = 25 },
        { bossName = "Ouro",                    requiredKills = 25 },
        { bossName = "Battleguard Sartura",     requiredKills = 35 },
        { bossName = "Fankriss the Unyielding", requiredKills = 65 },
        { bossName = "Viscidus",                requiredKills = 65 },
        { bossName = "C'Thun",                  requiredKills = 85 },
    },
    ["Ruins of Ahn'Qiraj!"] = {
        { bossName = "Ayamiss the Hunter",      requiredKills = 0 },
        { bossName = "Buru the Gorger",         requiredKills = 0 },
        { bossName = "Ossirian the Unscarred",  requiredKills = 0 },
    },
    ["Coilfang: Serpentshrine Cavern"] = {
        { bossName = "Hydross the Unstable",    requiredKills = 15 },
        { bossName = "The Lurker Below",        requiredKills = 20 },
        { bossName = "Leotheras the Blind",     requiredKills = 40 },
        { bossName = "Fathom-Lord Karathress",    requiredKills = 50 },
        { bossName = "Morogrim Tidewalker",    requiredKills = 60 },
        { bossName = "Lady Vashj",       requiredKills = 90 },
    },
    ["Tempest Keep"] = {
        { bossName = "Al'ar",    requiredKills = 20 },
        { bossName = "Void Reaver",        requiredKills = 40 },
        { bossName = "High Astromancer Solarian",    requiredKills = 40 },
        { bossName = "Kael'thas Sunstrider",    requiredKills = 65 },
    },
    ["Gruul's Lair"] = {
        { bossName = "High King Maulgar",                  requiredKills = 2 },
        { bossName = "Gruul the Dragonkiller",             requiredKills = 10 },
    },
    ["Magtheridon's Lair"] = {
        { bossName = "Maghteridon",                  requiredKills = 5 },
    },
    ["The Sunwell"] = {
        { bossName = "Kalecgos",    requiredKills = 30 },
        { bossName = "Brutallus",        requiredKills = 40 },
        { bossName = "Felmyst",     requiredKills = 40 },
        { bossName = "Eredar Twins",    requiredKills = 70 },
        { bossName = "M'uru",    requiredKills = 90 },
        { bossName = "Kil'jaeden",       requiredKills = 100 },
    },
    ["Zul'Aman"] = {
        { bossName = "Akil'zon",    requiredKills = 10 },
        { bossName = "Nalorakk",        requiredKills = 20 },
        { bossName = "Jan'alai",    requiredKills = 40 },
        { bossName = "Halazzi",    requiredKills = 50 },
        { bossName = "Hex Lord Malacrass",    requiredKills = 60 },
        { bossName = "Zul'jin",    requiredKills = 65 },
    },
}
