-- InstanceDungeonsData.lua
-- Diese Tabelle enthält für jeden klassischen Dungeon
-- Trage bei "requiredKills" die entsprechenden Zahlen ein.

InstanceDungeonsData = {
    ["Gnomeregan"] = {
        { bossName = "Viscous Fallout",       requiredKills = 5 },
        { bossName = "Electrocutioneer 6000", requiredKills = 25 },
        { bossName = "Crowd Pummeler 9-60",   requiredKills = 50 },
        { bossName = "Mekgineer Thermaplugg", requiredKills = 60 },
    },
    ["Deadmines"] = {
	    { bossName = "Rhahk'Zor",            requiredKills = 20 },
	    { bossName = "Sneed",                requiredKills = 40 },
	    { bossName = "Gilnid",               requiredKills = 55 },
	    { bossName = "Cookie",               requiredKills = 75 },
	    { bossName = "Mr.Smite",             requiredKills = 80 },
	    { bossName = "Captain Greenskin",    requiredKills = 85 },
        { bossName = "Edwin VanCleef",       requiredKills = 90 },
    },
    ["Stormwind Stockade"] = {
        { bossName = "Targorr the Dread",     requiredKills = 10 },
        { bossName = "Kam Deepfury",          requiredKills = 15 },
        { bossName = "Hamhock",               requiredKills = 20 },
        { bossName = "Bazil Thredd",          requiredKills = 25 },
        { bossName = "Dextren Ward",          requiredKills = 25 },
    },
    ["Ragefire Chasm"] = {
	    { bossName = "Oggleflint",           requiredKills = 20 },
	    { bossName = "Taragaman the Hungerer", requiredKills = 40 },
	    { bossName = "Jergosh the Invoker",  requiredKills = 50 },
	    { bossName = "Bazzalan",             requiredKills = 70 },
    },
    ["Razorfen Downs"] = {
	    { bossName = "Glutton",              requiredKills = 20 },
	    { bossName = "Tuten'kash",           requiredKills = 30 },
	    { bossName = "Mordresh Fire Eye",    requiredKills = 40 },
	    { bossName = "Ammenar the Coldbringer",requiredKills = 60 },
    },
    ["Razorfen Kraul"] = {
	    { bossName = "Aggem Thorncurse",     requiredKills = 30 },
	    { bossName = "Death Speaker Jargba", requiredKills = 35 },
	    { bossName = "Overlord Ramtusk",     requiredKills = 40 },
	    { bossName = "Agthelos the Raging",  requiredKills = 60 },
        { bossName = "Charlga Razorflank",   requiredKills = 65 },
    },
    ["Scarlet Monastery"] = {
	    { bossName = "High Inquisitor Fairbanks",     requiredKills = 30 },
	    { bossName = "High Inquisitor Whitemane", requiredKills = 40 },
	    { bossName = "Scarlet Commander Mograine",     requiredKills = 40 },
    },
    ["Shadowfang Keep"] = {
        { bossName = "Rethilgore",            requiredKills = 10 },
        { bossName = "Baron Silverlaine",     requiredKills = 30 },
        { bossName = "Commander Springvale",  requiredKills = 40 },
        { bossName = "Odo the Blindwatcher",  requiredKills = 50 },
        { bossName = "Fenrus the Devourer",   requiredKills = 60 },
        { bossName = "Wolfmaster Nandos",     requiredKills = 65 },
        { bossName = "Archmage Argus",        requiredKills = 65 },
    },
    ["Wailing Caverns"] = {
        { bossName = "Kresh",                 requiredKills = 10 },
        { bossName = "Lord Cobrahn",          requiredKills = 40 },
        { bossName = "Lord Pythas",           requiredKills = 50 },
        { bossName = "Skum",                  requiredKills = 60 },
        { bossName = "Verdan the Everliving", requiredKills = 70 },
        { bossName = "Lord Serpentis",        requiredKills = 70 },
        { bossName = "Mutanus the Devourer",   requiredKills = 90 },
    },
    ["Blackrock Depths"] = {
        { bossName = "Bael'Gar",	                requiredKills = 15},
        { bossName = "High Interrogator Gerstahn",  requiredKills = 15},
        { bossName = "Lord Roccor",	                requiredKills = 30},
        { bossName = "Lord Incendius",	            requiredKills = 35},
        { bossName = "Fineous Darkvire",            requiredKills = 45},
        { bossName = "Gorosh the Dervish",	        requiredKills = 45},
        { bossName = "Doom'rel",	                requiredKills = 55},
        { bossName = "Plugger Spazzring",           requiredKills = 75},
        { bossName = "Warder Stilgiss",	            requiredKills = 85},
        { bossName = "Phalanx",	                    requiredKills = 85},
        { bossName = "General Angerforge",	        requiredKills = 90},
        { bossName = "Golem Lord Argelmach",	    requiredKills = 95},
        { bossName = "Ambassador Flamelash",	    requiredKills = 100},
        { bossName = "Magmus",	                    requiredKills = 130},
        { bossName = "Emperor Dargran Thaurissan",	requiredKills = 145},
        },
    ["Scholomance"] = {
        { bossName = "Jandice Barov",   requiredKills = 45 },
        { bossName = "Marduk Blackpool",      requiredKills = 55 },
        { bossName = "Rattlegore", requiredKills = 65 },
        { bossName = "Vectus",          requiredKills = 65 },
        { bossName = "Ras Frosthwhisper", requiredKills = 80 },
        { bossName = "Instructor Malicia",  requiredKills = 100 },
        { bossName = "Doctor Theolen Krastinov", requiredKills = 105 },
        { bossName = "Lorekeeper Polkelt", requiredKills = 110 },
        { bossName = "Lady Illucia Barov",    requiredKills = 125 },
        { bossName = "Lord Alexei Barov", requiredKills = 135 },
        { bossName = "The Ravenian", requiredKills = 145 },
        { bossName = "Darkmaster Gandling",   requiredKills = 150 },
    },
    ["Stratholme"] = {
        { bossName = "Baroness Anastari", requiredKills = 30 },
        { bossName = "Nerub'enkan",         requiredKills = 30 },
        { bossName = "The Unforgiven",       requiredKills = 55 },
        { bossName = "Malor The Zealous",       requiredKills = 65 },
        { bossName = "Maleki the Pallid",    requiredKills = 65 },
        { bossName = "Canon Master Willey",     requiredKills = 85 },
        { bossName = "Archivist Galford",         requiredKills = 100 },
        { bossName = "Ramstein the Gorger",     requiredKills = 110 },
        { bossName = "Baron Rivendare",             requiredKills = 130 },
    },
    ["Uldaman"] = {
        { bossName = "Revelosh",              requiredKills = 10 },
        { bossName = "Baelog",             requiredKills = 15 },
        { bossName = "Ironaya",             requiredKills = 30 },
        { bossName = "Ancient Stone Keeper",  requiredKills = 35 },
        { bossName = "Galgann Firehammer",    requiredKills = 45 },
        { bossName = "Grimlok",             requiredKills = 60 },
        { bossName = "Archaedas",             requiredKills = 70 },
    },
    ["Zul'Farrak"] = {
        { bossName = "Theka the Martyr",        requiredKills = 25 },
        { bossName = "Antu'sul",              requiredKills = 35 },
        { bossName = "Witch Doctor Zum'rah",    requiredKills = 40 },
        { bossName = "Shadowpriest Sezz'ziz",   requiredKills = 65 },
        { bossName = "Nekrum Gutchewer",        requiredKills = 65 },
        { bossName = "Chief Ukorz Sandscalp",   requiredKills = 70 },
        { bossName = "Hydromancer Velrath",     requiredKills = 70 },
        { bossName = "Gahz'rilla",              requiredKills = 70 },
    },
    ["Auchindoun: Mana-Tombs"] = {
        { bossName = "Pandemonius",        requiredKills = 10 },
        { bossName = "Tavarok",              requiredKills = 40 },
        { bossName = "Nexus-Prince Shaffar",    requiredKills = 80 },
    },
    ["Auchindoun: Sethekk Halls"] = {
        { bossName = "Darkweaver Syth",        requiredKills = 25 },
        { bossName = "Anzu",              requiredKills = 50 },
        { bossName = "Talonking Ikiss",    requiredKills = 90 },
    },
    ["Auchindoun: Shadow Labyrinth"] = {
        { bossName = "Ambassador Hellmaw",        requiredKills = 30 },
        { bossName = "Blackheart the Inciter",   requiredKills = 50 },
        { bossName = "Grandmaster Vorpil",    requiredKills = 80 },
        { bossName = "Murmur",    requiredKills = 110 },
    },
    ["Auchindoun: Auchenai Crypts"] = {
        { bossName = "Shirrak the Dead Watcher",        requiredKills = 25 },
        { bossName = "Exarch Maladaar",              requiredKills = 50 },
    },
    ["Coilfang: The Underbog"] = {
        { bossName = "Hungarfen",        requiredKills = 15 },
        { bossName = "Ghaz'an",              requiredKills = 50 },
        { bossName = "Swamplord Musel'ek",    requiredKills = 65 },
        { bossName = "The Black Stalker",    requiredKills = 75 },
    },
    ["Coilfang: The Slave Pens"] = {
        { bossName = "Mennu the Betrayer",        requiredKills = 30 },
        { bossName = "Rokmar the Crackler",              requiredKills = 45 },
        { bossName = "Quagmirran",    requiredKills = 70 },
    },
    ["Coilfang: The Steamvault"] = {
        { bossName = "Hydromancer Thesoia",        requiredKills = 25 },
        { bossName = "Mekgineer Steamrigger",              requiredKills = 60 },
        { bossName = "Warlord Kalitresh",    requiredKills = 90 },
    },
    ["Hellfire Citadel: Ramparts"] = {
        { bossName = "Watchkeeper Gargolmar",        requiredKills = 35 },
        { bossName = "Omor the Unscarred",              requiredKills = 50 },
        { bossName = "Vazruden the Herald",    requiredKills = 60 },
    },
    ["Hellfire Citadel: The Blood Furnace"] = {
        { bossName = "The Maker",        requiredKills = 30 },
        { bossName = "Broggok",              requiredKills = 70 },
        { bossName = "Keli'dan the Breaker",    requiredKills = 90 },
    },
    ["Hellfire Citadel: The Shattered Halls"] = {
        { bossName = "Grand Warlock Nethekurse",        requiredKills = 70 },
        { bossName = "Blood Guard Porung",              requiredKills = 85 },
        { bossName = "Warbringer O'mrogg",        requiredKills = 120 },
        { bossName = "Warchief Kargath Bladefist",    requiredKills = 140 },
    },
    ["Tempest Keep: The Botanica"] = {
        { bossName = "Commander Sarannis",        requiredKills = 30 },
        { bossName = "High Botanist Freywinn",    requiredKills = 45 },
        { bossName = "Thorngrin the Tender",        requiredKills = 60 },
        { bossName = "Laj",              requiredKills = 85 },
        { bossName = "Warp Splinter",    requiredKills = 100 },
    },
    ["Tempest Keep: The Arcatraz"] = {
        { bossName = "Zereketh the Unbound",        requiredKills = 15 },
        { bossName = "Dalliah the Doomsayer",    requiredKills = 40 },
        { bossName = "Wrath-Scryer Soccothrates",        requiredKills = 40 },
        { bossName = "Harbinger Skyriss",              requiredKills = 60 },
    },
    ["Tempest Keep: The Mechanar"] = {
        { bossName = "Mechano-Lord",                    requiredKills = 20 },
        { bossName = "Nethermancer Sepethrea",          requiredKills = 30 },
        { bossName = "Pathaleon the Calculator",        requiredKills = 50 },
    },
   
    ["Azjol-Nerub"] = {
        { bossName = "Krik'thir the Gatewatcher",    requiredKills = 5 },
        { bossName = "Hadronox",        requiredKills = 15 },
        { bossName = "Anub'arak",    requiredKills = 35 },
    },
    ["Utgarde Keep"] = {
        { bossName = "Prince Keleseth",    requiredKills = 15 },
        { bossName = "Dalronn the Controller",        requiredKills = 40 },
        { bossName = "Ingvar the Plunderer",    requiredKills = 60 },
    },
    ["The Nexus"] = {
        { bossName = "Grand Magus Telestra",    requiredKills = 20 },
        { bossName = "Anomalus",        requiredKills = 50 },
        { bossName = "Ormorokk the Tree-Shaper",    requiredKills = 90 },
        { bossName = "Keristrasza",    requiredKills = 110 },
    },
    ["Ahn'kahet: The Old Kingdom"] = {
        { bossName = "Elder Nadox",    requiredKills = 15 },
        { bossName = "Prince Taldaraan",        requiredKills = 30 },
        { bossName = "Amanitar",    requiredKills = 40 },
        { bossName = "Jedoga Shadowseeker",    requiredKills = 50 },
        { bossName = "Herold Volazj",    requiredKills = 55 },
    },
    ["Halls of Lightning"] = {
        { bossName = "General Bjarngrim",    requiredKills = 5 },
        { bossName = "Volkhan",        requiredKills = 30 },
        { bossName = "Ionar",    requiredKills = 50 },
        { bossName = "Loken",    requiredKills = 75 },
    },
    ["Halls of Stone"] = {
        { bossName = "Krystallus",    requiredKills = 40 },
        { bossName = "Maiden of Grief",        requiredKills = 60 },
        { bossName = "Sjonnar the Ironshaper",    requiredKills = 80 },
    },
    ["Gundrak"] = {
        { bossName = "Eck the Ferocious", requiredKills = 0 },
        { bossName = "Moorabi",    requiredKills = 5 },
        { bossName = "Draakari Elemental",        requiredKills = 10 },
        { bossName = "Slad'ran",    requiredKills = 25 },
        { bossName = "Gal'Darah",    requiredKills = 35 },
    },
      

}

